### ISSUE TITLE
.inf file 

### ISSUE THREAD

**Issue by TadasLes** [r2axz/bluepill-serial-monster#10]
Tested on W7 and W8. It seems, driver .inf file is necessary to extend usable OS range.
Thank you
Tadas LY1CE

**Comment by r2axz** [comment]
Thank you for your report! I haven't tested the firmware on those. I should have, though. You right, an inf file is needed to make it work. I will address this issue shortly.

**Comment by r2axz** [comment]
@TadasLes Would you mind testing the inf file when it is ready. I have a Windows 7 VM and I'm going use it for testing, but it would be nice if you can confirm the inf file works on Windows 8 as well.

**Comment by TadasLes** [comment]
> @TadasLes Would you mind testing the inf file when it is ready. I have a Windows 7 VM and I'm going use it for testing, but it would be nice if you can confirm the inf file works on Windows 8 as well.

Of course I will test it on W7, W8 and W XP

**Comment by r2axz** [comment]
@TadasLes Thank you! I really appreciate that. I think the inf file will be available either later today, or during the weekend.

**Comment by r2axz** [comment]
@TadasLes Looks like I managed to create an INF file that works just fine on Windows 7 x64. Could you please test it on your set of operating systems?

Here is how I do it on Windows 7 x64:

Method 1

1. Copy both inf and cat files to your machine;
2. Open the Command Prompt with administrative privileges;
3. Run the following command:

```cmd
pnputil -i -a stm32-blue-pill-serial-monster.inf
```

It should warn you that you are installing a driver from an unidentified developer. That's OK, the driver has been signed with a self-signed cert.

4. Plug in the device. Windows will first try to find the driver in Windows Update, and after that will install the local driver you just installed.

Method 2

Go to the Device Manager, right click on one of the STM32 Blue Pill Serial Monster devices, and select Update Driver Software. Then choose browse my computer for driver software and point it to a directory with the inf file. Windows will install the driver for one of the CDC devices. You don't need to repeat the procedure for the others. Just disconnect and reconnect the device and Windows will pick up the rest of the ports.

See below for the inf file archive.

[inf.zip](https://github.com/r2axz/bluepill-serial-monster/files/5576273/inf.zip)

**Comment by r2axz** [comment]
@TadasLes I tested on Windows XP 32 bit myself. Everything's OK.

**Comment by r2axz** [comment]
I bought a code-signing certificate from Comodo. As soon as they complete their validation stuff, I will sign the inf.

**Comment by TadasLes** [comment]
XP x32 and W7 x32 - OK
W8 x64 - the system interrupts installation without valid driver certificate. There isn't branch for installing non certified driver.

**Comment by TadasLes** [comment]
Hope, with certified driver things will be OK.

**Comment by r2axz** [comment]
@TadasLes Thank you very much for testing. I will get back to you when my certificate is ready.

If you don't mind, what's your use case for the firmware?

**Comment by r2axz** [comment]
@TadasLes I added signed cat file. Now it should work on Win 8 as well. Could you please re-test?
[inf.zip](https://github.com/r2axz/bluepill-serial-monster/files/5582573/inf.zip)

**Comment by r2axz** [comment]
I also tested it on Win 8 x64 myself. Now it works OK.

**Comment by TadasLes** [comment]
Hi, tested signed driver on W8 x64. Install successful.
I'm planning add to BluePill level shifters on lines that are not 5V tolerant for safety.
It will be fine tool for debugging systems with UART. No more single USB <-> UART converters.
:1st_place_medal:

**Comment by r2axz** [comment]
@TadasLes Thank you very much for testing. And thank you for describing the use-case, that's interesting. Looks like we're all set, I am closing the issue and merging the pull-request.
