### ISSUE TITLE
Non-free library dependency 

### ISSUE THREAD

**Issue by zoobab** [r2axz/bluepill-serial-monster#26]
Hi,

This GPLed project depends on a non-free library (SMT32CubeF1), where the USB stack is licensed under the ST SLA0044:

https://github.com/STMicroelectronics/STM32CubeF1/blob/master/License.md

Like we did for the DirtyJTAG project, you could use free libraries like the unicore-mx or libopencm3.

I could try to change the underlying library.

**Comment by r2axz** [comment]
I don't use the USB stack from SMT32CubeF1, this project implements the entire USB stack itself.

**Comment by r2axz** [comment]
@zoobab This project uses CMSIS only, which I believe is open. CMSIS uses Apache license so there is no any problems.

**Comment by zoobab** [comment]
OK, if you only use the CMSIS library from ARM, is it possible to modify the build instructions to only use CMSIS? 

https://github.com/ARM-software/CMSIS_5

**Comment by r2axz** [comment]
Sounds reasonable, thank you. I will implement this at some point.

**Comment by zoobab** [comment]
I removed everything except "STM32CubeF1/Drivers/CMSIS", and it still builds. Will try with CMSIS_5 now...

**Comment by r2axz** [comment]
Thank you for this.

**Comment by zoobab** [comment]
Ideally, via a "git submodule", although after 10 years this feature of git still sucks.

**Comment by r2axz** [comment]
You probably right. I will do this. Most likely during the weekend. Pretty busy with my work-work at the moment. Thanks!

**Comment by r2axz** [comment]
Turns out https://github.com/ARM-software/CMSIS_5 is not enough. bluebill-serial-monster uses vendor-specific CMSIS definitions from STM. However, those definitions are distributed under BSD 3-Clause license so there is no non-free library dependencies in the project. Again, I don't use the STM USB stack. Closing the issue.
