### ISSUE TITLE
Probably erroneous usb_endpoint_address_cdc_0_interrupt usage 

### ISSUE THREAD

**Issue by vnodeng** [r2axz/bluepill-serial-monster#58]
The usb_descriptors.c file at line 333 refers to the usb_endpoints parameters array via usb_endpoint_address_cdc_0_interrupt constant, which is a bit suspicious because this is done in the descriptor of third UART. This doesn't affect current functionality because parameters of control endpoints happens to match, but introduces minor inconsistency.

**Comment by r2axz** [comment]
Yes, you are right. I actually also noticed this and already fixed in #57.

**Comment by vnodeng** [comment]
Ok, missed it, because github search is a bit flawed regarding the pull request details.
