### ISSUE TITLE
[info] max baud rate

### ISSUE THREAD

**Issue by yashikada** [r2axz/bluepill-serial-monster#61]
what is the maximum baud rate you have achieved on a uart?
I would like to avoid buying an expensive ftdi ft232h.

Thank you

**Comment by r2axz** [comment]
Please see README.md

>> Supports all baud rates up to 2 MBaud;

I have no idea what baud rate you need, but ft232h is notably faster.

**Comment by yashikada** [comment]
Thank you @r2axz for informations and sorry for the delay.
Your README has many informations, so it's not easy read all.
In this case baud is a bit, rigth? So max speed is 2 Mbit/s while a ft232h reaches 12Mbaud (UART) up to 40MB/s (Sync FIFO).
2 Mbit/s is a good speed for me.

**Comment by r2axz** [comment]
> In this case baud is a bit, rigth? So max speed is 2 Mbit/s while a ft232h reaches 12Mbaud (UART) up to 40MB/s (Sync FIFO).
2 Mbit/s is a good speed for me.

Yes, this is correct.
